services:
  python:
    build: ../app
    ports:
      - 8080:8080

  nginx:
    depends_on:
      - python
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "pltxc.com"
      SITES: "pltxc.com=python:8080"

volumes:
  ssl_data:
