[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "mangum>=0.19.0",
    "uvicorn>=0.34.0",
    "uvloop>=0.21.0",
]
