testvar: me
service_user: service
authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDG70oCAVa5keq71QmL13uuVVxFM8pBRwQZVm/LShPGhNjNxZI3p6VAGT85i3uleOx0Na07D9kPZOiRtFAjWC95qAPPIXOAZo33MfrrbRIO8eCWw7JTaFc2jDuxV5JIrIeXjfwToxUuEW3mjbVbYTAc9ISqkQVnANu9yUEUNi+ejhX/aGje392QXGtqKFv2j40avyQqDM3MdEB1gBUwbqByRfaeyHvnot3b5dkMkIIH0kOu4UzSybdonkrtbIXrlF+GV0a+uEy6vw5T8rItY5IqAwdZVtwnxWUIPf3PJhXe/z2yRlwi7yTtKdXrFtLVFKBfs4yRGLZunVymHRODAZYQ4mwuXQqxyTA/VvVQ1AWluLegnyvW2O0FYoBxuTySQfYj79b0+ahbBDHo3F4okpeZm0WBSFdA1guiYurT50Bzz1D9+tsLJqUCx1DkgSZ+1satCbcgXx3WWxRUPvZn6ulLidDT3uWfhywhe/XhFzjigiXRXFHYxjln8NFEJuaZids= mpvanwinkle@gmail.com"
letsencrypt_email: mike@mikevanwinkle.com

services:
  - service_name: test-app
    service_host: test-app.wordleaguer.com
    service_path: "{{ playbook_dir }}/../app"
    service_upstream: 0.0.0.0
    service_port: 8080
    use_ssl: true

allowips: []

# allowips:
# - 173.245.48.0/20
# - 103.21.244.0/22
# - 103.22.200.0/22
# - 103.31.4.0/22
# - 141.101.64.0/18
# - 108.162.192.0/18
# - 190.93.240.0/20
# - 188.114.96.0/20
# - 197.234.240.0/22
# - 198.41.128.0/17
# - 162.158.0.0/15
# - 104.16.0.0/13
# - 104.24.0.0/14
# - 172.64.0.0/13
# - 131.0.72.0/22
# - 100.101.179.69/32 # tailnet wink-edge
# - 192.168.0.0/16
# - 127.0.0.1/32
# - 96.126.101.30/32

python_version: 3.13
